# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import operation_pb2 as operation__pb2


class SumServiceStub(object):
    """Servicio específico para operaciones de suma
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sum = channel.unary_unary(
                '/operations.SumService/Sum',
                request_serializer=operation__pb2.SumRequest.SerializeToString,
                response_deserializer=operation__pb2.SumResponse.FromString,
                )
        self.CheckStatus = channel.unary_unary(
                '/operations.SumService/CheckStatus',
                request_serializer=operation__pb2.StatusRequest.SerializeToString,
                response_deserializer=operation__pb2.StatusResponse.FromString,
                )
        self.GetAsyncOperationStatus = channel.unary_unary(
                '/operations.SumService/GetAsyncOperationStatus',
                request_serializer=operation__pb2.AsyncOperationRequest.SerializeToString,
                response_deserializer=operation__pb2.AsyncOperationResponse.FromString,
                )


class SumServiceServicer(object):
    """Servicio específico para operaciones de suma
    """

    def Sum(self, request, context):
        """Operación síncrona de suma
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckStatus(self, request, context):
        """Verificación de estado del servicio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAsyncOperationStatus(self, request, context):
        """Consulta de estado de una operación asíncrona
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SumServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sum': grpc.unary_unary_rpc_method_handler(
                    servicer.Sum,
                    request_deserializer=operation__pb2.SumRequest.FromString,
                    response_serializer=operation__pb2.SumResponse.SerializeToString,
            ),
            'CheckStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStatus,
                    request_deserializer=operation__pb2.StatusRequest.FromString,
                    response_serializer=operation__pb2.StatusResponse.SerializeToString,
            ),
            'GetAsyncOperationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAsyncOperationStatus,
                    request_deserializer=operation__pb2.AsyncOperationRequest.FromString,
                    response_serializer=operation__pb2.AsyncOperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'operations.SumService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SumService(object):
    """Servicio específico para operaciones de suma
    """

    @staticmethod
    def Sum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/operations.SumService/Sum',
            operation__pb2.SumRequest.SerializeToString,
            operation__pb2.SumResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/operations.SumService/CheckStatus',
            operation__pb2.StatusRequest.SerializeToString,
            operation__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAsyncOperationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/operations.SumService/GetAsyncOperationStatus',
            operation__pb2.AsyncOperationRequest.SerializeToString,
            operation__pb2.AsyncOperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SubtractServiceStub(object):
    """Servicio específico para operaciones de resta
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subtract = channel.unary_unary(
                '/operations.SubtractService/Subtract',
                request_serializer=operation__pb2.SubtractRequest.SerializeToString,
                response_deserializer=operation__pb2.SubtractResponse.FromString,
                )
        self.CheckStatus = channel.unary_unary(
                '/operations.SubtractService/CheckStatus',
                request_serializer=operation__pb2.StatusRequest.SerializeToString,
                response_deserializer=operation__pb2.StatusResponse.FromString,
                )
        self.GetAsyncOperationStatus = channel.unary_unary(
                '/operations.SubtractService/GetAsyncOperationStatus',
                request_serializer=operation__pb2.AsyncOperationRequest.SerializeToString,
                response_deserializer=operation__pb2.AsyncOperationResponse.FromString,
                )


class SubtractServiceServicer(object):
    """Servicio específico para operaciones de resta
    """

    def Subtract(self, request, context):
        """Operación síncrona de resta
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckStatus(self, request, context):
        """Verificación de estado del servicio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAsyncOperationStatus(self, request, context):
        """Consulta de estado de una operación asíncrona
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubtractServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subtract': grpc.unary_unary_rpc_method_handler(
                    servicer.Subtract,
                    request_deserializer=operation__pb2.SubtractRequest.FromString,
                    response_serializer=operation__pb2.SubtractResponse.SerializeToString,
            ),
            'CheckStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStatus,
                    request_deserializer=operation__pb2.StatusRequest.FromString,
                    response_serializer=operation__pb2.StatusResponse.SerializeToString,
            ),
            'GetAsyncOperationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAsyncOperationStatus,
                    request_deserializer=operation__pb2.AsyncOperationRequest.FromString,
                    response_serializer=operation__pb2.AsyncOperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'operations.SubtractService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SubtractService(object):
    """Servicio específico para operaciones de resta
    """

    @staticmethod
    def Subtract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/operations.SubtractService/Subtract',
            operation__pb2.SubtractRequest.SerializeToString,
            operation__pb2.SubtractResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/operations.SubtractService/CheckStatus',
            operation__pb2.StatusRequest.SerializeToString,
            operation__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAsyncOperationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/operations.SubtractService/GetAsyncOperationStatus',
            operation__pb2.AsyncOperationRequest.SerializeToString,
            operation__pb2.AsyncOperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
